apiVersion: v1
kind: ServiceAccount
metadata:
    labels:
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: postk8s
    name: postk8s-controller-manager
    namespace: {{ .Release.Namespace }}
